//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugReport
    {
        public int Id { get; set; }
        public string ReportingAspNetUserId { get; set; }
        public string BuggedUrl { get; set; }
        public string Message { get; set; }
        public string BrowserInfo { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
