//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CloudFile()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.RecipeCloudFiles = new HashSet<RecipeCloudFile>();
            this.RecipeStepsCloudFiles = new HashSet<RecipeStepsCloudFile>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public string FileExtension { get; set; }
        public string CreatorId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CloudFilesThumbnail CloudFilesThumbnail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeCloudFile> RecipeCloudFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeStepsCloudFile> RecipeStepsCloudFiles { get; set; }
    }
}
