//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowingChef
    {
        public string AspNetUserId { get; set; }
        public string FollowingChefId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Chef Chef { get; set; }
        public virtual Chef Chef1 { get; set; }
    }
}
