//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.RecipeStepsIngredients = new HashSet<RecipeStepsIngredient>();
        }
    
        public string IngredientName { get; set; }
        public Nullable<int> CloudFileId { get; set; }
        public string CreatorId { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CloudFile CloudFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeStepsIngredient> RecipeStepsIngredients { get; set; }
    }
}
