//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecipeStep()
        {
            this.RecipeStepsCloudFiles = new HashSet<RecipeStepsCloudFile>();
            this.RecipeStepsIngredients = new HashSet<RecipeStepsIngredient>();
        }
    
        public int RecipeId { get; set; }
        public int StepNumber { get; set; }
        public string Comment { get; set; }
        public long EstimatedTimeInSeconds { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeStepsCloudFile> RecipeStepsCloudFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeStepsIngredient> RecipeStepsIngredients { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
