//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.RecipeFlags = new HashSet<RecipeFlag>();
            this.RecipeSteps = new HashSet<RecipeStep>();
            this.Comments = new HashSet<Comment>();
            this.DietaryRestrictions = new HashSet<DietaryRestriction>();
            this.RecipeCloudFiles = new HashSet<RecipeCloudFile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CreationStep { get; set; }
        public string Description { get; set; }
        public int ServingSize { get; set; }
        public string CreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string ViewableType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeFlag> RecipeFlags { get; set; }
        public virtual RecipeViewableType RecipeViewableType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeStep> RecipeSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietaryRestriction> DietaryRestrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeCloudFile> RecipeCloudFiles { get; set; }
    }
}
