//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeFlag
    {
        public int RecipeId { get; set; }
        public string ReportingAspNetUserId { get; set; }
        public string FlagName { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Flag Flag { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
