//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeStepsIngredient
    {
        public string IngredientName { get; set; }
        public int RecipeId { get; set; }
        public int StepNumber { get; set; }
        public string Amount { get; set; }
        public string MeasurementUnitName { get; set; }
        public string ToAmount { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual RecipeStep RecipeStep { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
    }
}
