//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceCooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedRecipe
    {
        public string AspNetUserId { get; set; }
        public int RecipeId { get; set; }
        public System.DateTime SavedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
